name: Shell Cmds
on: [push, push]
jobs:
  run-shell-cmd:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Goodbye World"
      - name: multiline script
        run: |
          node -v
          npm -v
